### ISSUE TITLE
Collect feedback from OpenSUSE Leap 42.2 users on compilation

### ISSUE THREAD

**Issue by sradl1981** [NanoSim/Porto#5]
There are minor differences when compiling with OpenSUSE, as well as some missing things in the installation manual that need update.

also, some modules cannot be compiled (e.g., GSL)

**Comment by sradl1981** [comment]
Description of how to correctly define SOFTBASE and LD_LIBRARY_PATH in .bashrc  is missing in the soft5 manual.

Should be:
export SOFTBASE=/usr/local/soft5
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SOFTBASE/lib64:$SOFTBASE/lib64/soft5/storage:$SOFTBASE/lib64/soft5/plugins:$HOME/NanoSim/build-soft5/usr/lib64/
export PATH=$PATH:$SOFTBASE/bin

**Comment by sradl1981** [comment]
Documentation is misleading: remarc-wrapper has been replaced by 
~/NanoSim/run-soft5/examples/remarc/rmc-vasp.sh
Why not updating the documentation to safe a lot of time of (potential) users?

**Comment by sradl1981** [comment]
Configuration options (using ccmake) look like the following (used by OpenSUSE user, works almost fine)

BUILD_GTEST                      ON
 BUILD_HD5                        OFF
 BUILD_MONGOC                     ON
 BUILD_TESTING                    OFF
 CMAKE_BUILD_TYPE                 Debug
 CMAKE_INSTALL_PREFIX             /usr/local/soft5
 HDF5_DIR                         /home/sradl/NanoSim/build-soft5/usr/share/cmake
 Qt5Concurrent_DIR                /usr/lib64/cmake/Qt5Concurrent
 Qt5Core_DIR                      /usr/lib64/cmake/Qt5Core
 Qt5Network_DIR                   /usr/lib64/cmake/Qt5Network
 Qt5Script_DIR                    /usr/lib64/cmake/Qt5Script
 USE_PYTHON3                      OFF
 VALGRIND                         /home/sradl/bin/valgrind
 WITH_FOREIGN_C                   OFF
 WITH_FOREIGN_FORTRAN             OFF
 WITH_FOREIGN_PYTHON              OFF
 WITH_HSM                         OFF
 WITH_NUMERICS                    ON
 WITH_PLUGIN_GSL                  ON
 WITH_PLUGIN_HD5                  OFF
 WITH_PLUGIN_MONGO                ON
 WITH_PLUGIN_NLOPT                ON
 WITH_PLUGIN_SOFT_KERNEL          ON
 WITH_PORTO                       ON
 WITH_STORAGE_EXTERNAL            ON
WITH_STORAGE_HD5                 OFF
 WITH_STORAGE_JSON                ON
 WITH_STORAGE_MONGO               ON
 WITH_TESTS                       ON
 WITH_WEB                         ON

**Comment by sradl1981** [comment]
sradl to update this files here
https://github.com/NanoSim/Porto/tree/porto/Preview-Final-Release/doc/manual

in the above we should only switch WITH_PORT ON and BUILD_MONGOC ON. we do not need other options

**Comment by tankefugl** [comment]
This can also be resolved by making BUILD_MONGOC implied by WITH_PORTO

**Comment by sradl1981** [comment]
a reference to the most essential features of mongoDB should be made in the manual:
https://docs.mongodb.com/manual/introduction/

**Comment by sradl1981** [comment]
all tests now run on an OpenSUSE Leap 42.2 machine. docu is fine with some minor updates in this fork: https://github.com/sradl1981/SOFT5
