### ISSUE TITLE
version of 'libgtest-dev' unclear: cannot compile 'porto/test/parscale/parscale-test'

### ISSUE THREAD

**Issue by sradl1981** [NanoSim/Porto#6]
during make on an OpenSUSE Leap 42.2 machine, compilation fails at
[ 94%] Linking CXX executable parscale-test
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libgtest.so: undefined reference to `pthread_key_create'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libgtest.so: undefined reference to `pthread_getspecific'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libgtest.so: undefined reference to `pthread_key_delete'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libgtest.so: undefined reference to `pthread_setspecific'
collect2: error: ld returned 1 exit status
porto/test/parscale/CMakeFiles/parscale-test.dir/build.make:147: recipe for target 'porto/test/parscale/parscale-test' failed
make[2]: *** [porto/test/parscale/parscale-test] Error 1
CMakeFiles/Makefile2:3453: recipe for target 'porto/test/parscale/CMakeFiles/parscale-test.dir/all' failed
make[1]: *** [porto/test/parscale/CMakeFiles/parscale-test.dir/all] Error 2

The installed googletest-dev library is

googletest-devel-1.7.0-26.2.x86_64

**Comment by sradl1981** [comment]
This is a problem in the documentation, since it appears that libgtest-dev is not needed, and the self-compiled gtest library must be installed using a different command. Can be fixed with improved docu

**Comment by quaat** [comment]
The current documentation supports Ubuntu 16.04 3LTS. We haven't looked into OpenSUSE yet.

**Comment by tankefugl** [comment]
We might want to include gtest on a source code leve, as a part of the repository. This will ensure that gtest is compiled correctly regardless of the system.

**Comment by sradl1981** [comment]
can be solved by mentioning BUILD_GTEST ON in the documentation, Later, tankefugl will include the whole gtest package as src code anyhow, and we simply remove it again from the docu
