### ISSUE TITLE
remove "dead" code

### ISSUE THREAD

**Issue by sradl1981** [NanoSim/Porto#9]
I guess this is outdated and has been replaced
https://github.com/NanoSim/Porto/tree/porto/Preview-Final-Release/porto/src/remark-wrapper

potentially many more things that are outdated that should be deleted.

**Comment by sradl1981** [comment]
stefan to go on and just delete what he thinks is removable. commiting will be anyhow issue-based

**Comment by tankefugl** [comment]
This has been resolved in the internal repository. The fix will be pushed to GitHub at a later stage.
